language: java
jdk:
  - oraclejdk8
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.25.1/hugo_0.25.1_Linux-64bit.deb
  - sudo dpkg -i hugo_0.25.1_Linux-64bit.deb
  - nvm install 8
script:
  - cd ./app && yarn run build
  - cd ../ && ./docs.sh
  - cd hugo
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  target_branch: gh-pages
cache:
  - yarn
